services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./public:/var/www/public
      - ./database:/var/www/database
      - storage_data:/var/www/storage     # Use Docker volume for storage
      - cache_data:/var/www/bootstrap/cache  # Use Docker volume for cache
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
  storage_data:     # Define the Docker volume for storage
  cache_data:       # Define the Docker volume for cache
